#!/usr/bin/env python
"""
Merge Oligo Count Results from Array Job

This script merges all individual count CSV files generated by the parallel
oligo counter array job into a single consolidated file.

The merge performs a simple horizontal concatenation, preserving the exact
oligo order from the original files.

Usage:
    python merge_oligo_counts.py -r results -o output_prefix [-v]
"""

import pandas as pd
import os
import sys
import glob
import argparse
from pathlib import Path
import re

def extract_folder_name_from_path(csv_path):
    """
    Extract the folder name from the CSV file path.
    
    Example:
        results/oligo_counts_TcC1_folder_task1/TcC1_folder.counts.csv
        -> returns 'TcC1_folder'
    """
    # Get the parent directory name
    parent_dir = os.path.basename(os.path.dirname(csv_path))
    
    # Try to extract the original folder name from the task directory name
    # Pattern: {prefix}_{folder_name}_task{number}
    match = re.search(r'.*?_(.*?)_task\d+$', parent_dir)
    if match:
        return match.group(1)
    
    # Fallback: use the CSV filename without extension
    csv_filename = os.path.basename(csv_path)
    # Remove .counts.csv extension
    if csv_filename.endswith('.counts.csv'):
        return csv_filename[:-11]
    
    return os.path.splitext(csv_filename)[0]

def find_count_files(results_dir):
    """
    Find all count CSV files in the results directory structure.
    
    Args:
        results_dir: Path to the results directory
        
    Returns:
        List of tuples (csv_path, folder_name)
    """
    # Find all count CSV files
    pattern = os.path.join(results_dir, "*", "*.counts.csv")
    csv_files = glob.glob(pattern)
    
    if not csv_files:
        # Try alternative pattern in case of different structure
        pattern = os.path.join(results_dir, "*.counts.csv")
        csv_files = glob.glob(pattern)
    
    # Sort files for consistent ordering
    csv_files.sort()
    
    # Extract folder names for column headers
    file_info = []
    for csv_file in csv_files:
        folder_name = extract_folder_name_from_path(csv_file)
        file_info.append((csv_file, folder_name))
    
    return file_info

def merge_count_files(results_dir, output_prefix, verbose=False):
    """
    Merge all count CSV files from array job results.
    
    Performs a simple horizontal concatenation of all CSV files.
    All files should have the same oligos in the same order.
    
    Args:
        results_dir: Directory containing the count results
        output_prefix: Prefix for output files
        verbose: Print detailed progress information
        
    Returns:
        Path to the merged output file
    """
    
    print("=" * 60)
    print("Starting Merge of Oligo Count Results")
    print("=" * 60)
    print(f"Results directory: {results_dir}")
    print(f"Output prefix: {output_prefix}")
    print()
    
    # Check if results directory exists
    if not os.path.exists(results_dir):
        print(f"ERROR: Results directory '{results_dir}' not found!")
        sys.exit(1)
    
    # Find all count files
    file_info = find_count_files(results_dir)
    
    if not file_info:
        print(f"ERROR: No count CSV files found in {results_dir}")
        print("Expected pattern: */**.counts.csv")
        sys.exit(1)
    
    print(f"Found {len(file_info)} CSV files to merge:")
    print()
    
    # Read all CSV files
    all_dfs = []
    sample_names = []
    
    for csv_file, folder_name in file_info:
        if verbose:
            print(f"  Reading: {csv_file}")
            print(f"    -> Sample name: {folder_name}")
        else:
            print(f"  Processing: {folder_name}")
        
        try:
            # Read CSV file
            df = pd.read_csv(csv_file, index_col=0)
            
            # Get the column name (should be single column per file)
            if len(df.columns) == 1:
                # Rename column to folder name
                df.columns = [folder_name]
            else:
                # Multiple columns - prefix with folder name
                df.columns = [f"{folder_name}_{col}" for col in df.columns]
            
            all_dfs.append(df)
            sample_names.append(folder_name)
            
        except Exception as e:
            print(f"WARNING: Failed to read {csv_file}: {e}")
            continue
    
    if not all_dfs:
        print("ERROR: No valid CSV files could be read!")
        sys.exit(1)
    
    print()
    print("Merging dataframes...")
    
    # Simple horizontal concatenation - preserves oligo order
    try:
        merged_df = pd.concat(all_dfs, axis=1)
        
        # Verify all indices are identical (same oligos in same order)
        if verbose:
            first_index = all_dfs[0].index
            all_match = True
            for i, df in enumerate(all_dfs[1:], 1):
                if not df.index.equals(first_index):
                    print(f"WARNING: Index mismatch in file {i+1}")
                    all_match = False
            if all_match:
                print("✓ All files have identical oligo order")
        
    except Exception as e:
        print(f"ERROR: Failed to merge dataframes: {e}")
        sys.exit(1)
    
    # Save merged results - preserving original oligo order
    output_file = f"{output_prefix}_merged_all_samples.csv"
    merged_df.to_csv(output_file)
    print(f"Merged results saved to: {output_file}")
    
    # Print summary statistics
    print()
    print("=" * 60)
    print("Summary Statistics")
    print("=" * 60)
    print(f"Total samples merged: {len(merged_df.columns)}")
    print(f"Total oligos tracked: {len(merged_df)}")
    print()
    
    # Sample-wise statistics (in processing order)
    print("Counts per sample:")
    print("-" * 40)
    for sample in merged_df.columns:
        count = merged_df[sample].sum()
        print(f"  {sample:30s}: {int(count):>12,}")
    
    print()
    print("Overall statistics:")
    print("-" * 40)
    print(f"  Total counts across all samples: {int(merged_df.sum().sum()):,}")
    print(f"  Average counts per sample: {int(merged_df.sum().mean()):,}")
    print(f"  Min counts in a sample: {int(merged_df.sum().min()):,}")
    print(f"  Max counts in a sample: {int(merged_df.sum().max()):,}")
    
    # Oligo detection statistics
    print()
    print("Oligo detection:")
    print("-" * 40)
    oligos_detected = (merged_df > 0).sum(axis=1)
    print(f"  Oligos found in all samples: {(oligos_detected == len(merged_df.columns)).sum()}")
    print(f"  Oligos found in no samples: {(oligos_detected == 0).sum()}")
    print(f"  Average samples per oligo: {oligos_detected.mean():.1f}")
    
    # Save summary report
    summary_file = f"{output_prefix}_merge_summary.txt"
    with open(summary_file, 'w') as f:
        f.write("Merge Summary Report\n")
        f.write("=" * 60 + "\n")
        f.write(f"Total samples merged: {len(merged_df.columns)}\n")
        f.write(f"Total oligos tracked: {len(merged_df)}\n")
        f.write(f"Output file: {output_file}\n")
        f.write("\nSamples processed (in order):\n")
        for sample in sample_names:
            f.write(f"  - {sample}\n")
        f.write("\nCounts per sample:\n")
        for sample in merged_df.columns:
            count = merged_df[sample].sum()
            f.write(f"  {sample}: {int(count):,}\n")
    
    print()
    print(f"Summary report saved to: {summary_file}")
    
    print()
    print("=" * 60)
    print("MERGE COMPLETE!")
    print("=" * 60)
    
    return output_file

def main():
    parser = argparse.ArgumentParser(
        description='Merge oligo count results from parallel array job',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This script performs a simple horizontal concatenation of count files.
It preserves the exact oligo order from the original files.

Examples:
  # Basic usage
  python %(prog)s -r results -o my_project
  
  # With verbose output
  python %(prog)s -r results -o my_project -v
  
  # Custom results directory
  python %(prog)s -r /path/to/results -o experiment1
        """
    )
    
    parser.add_argument('-r', '--results-dir', default='results',
                        help='Directory containing count results (default: results)')
    parser.add_argument('-o', '--output-prefix', required=True,
                        help='Prefix for output files')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='Print verbose output')
    
    args = parser.parse_args()
    
    # Run the merge
    output_file = merge_count_files(
        results_dir=args.results_dir,
        output_prefix=args.output_prefix,
        verbose=args.verbose
    )
    
    return 0

if __name__ == "__main__":
    sys.exit(main())